config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, 	 :controllers => { :registrations => 'users/registrations', :sessions =>'users/sessions' }
  root "home#index"
  get 'home' => 'home#index'

  get '/notification' => 'home#notification', as: :notice
  delete '/notification/:id' => 'notification#destroy', as: :notification
  delete '/delete_all_notification/:id' => 'notification#delete_all', as: :delete_all

  resources :home, only: [:delete_notice] do
    collection do
      delete :delete_notice
    end
  end

  get 'admin/teamlead' => 'admin#teamlead'
  get 'admin/developers' => 'admin#developer'
  get 'admin/tester' => 'admin#tester'
  get 'admin/make_tt/:id' => 'admin#make_tt', as: :make_tt
  get 'admin/make_dp/:id' => 'admin#make_dp', as: :make_dp
  get 'assign_employee/:id' =>'admin#assign_employee', as: :assign_employee
   get 'admin/showa/:id' =>  'requirement#showa', as: :showa

  get 'teamlead/tester' => 'teamlead#tester'
  get 'teamlead/developers' => 'teamlead#developer'

  get 'make_task_tl/:id' => 'teamlead#make_task_tl', as: :make_task_tl

  resources :requirement
  patch 'admin/make_teamlead/:id' => 'admin#make_teamlead', as: :make_teamlead
  delete 'admin/employee/:id' => 'employee#destroy',        as: :admin_employee

  resources :task
  patch 'close_task/:id' => 'task#close_task', as: :close_task
  patch 'reopen_task/:id' => 'task#reopen_task', as: :reopen_task



  resources :teamlead, only: [:tl_assign_to_multiple] do
    collection do
      put :tl_assign_to_multiple
      put :tl_assign
    end
  end

  resources :admin, only: [:edit_project_multiple, :update_project_multiple] do
    collection do
      get :edit_project_multiple, as: :edit_project_multiple
      put :update_project_multiple, as: :update_project_multiple
      put :assign_employee_put,     as: :assign_employee_put
    end
  end

  resources :developer, only: [:done_multiple_update] do
    collection do
      put :done_multiple_update, as: :done_multiple_update
    end
  end

  resources :tester, only: [:done_multiple_update] do
    collection do
      put :done_multiple_update, as: :done_multiple_update
    end
  end

  

  get 'add_task/:id' => 'teamlead#add_task', as: :add_task
  
end

app/models/teamlead.rb
class Teamlead < ApplicationRecord
	has_many :users
	has_many :tasks
	has_many :requirements
end

# Team lead table does not have admin in it
# It has user_id that tells manager of the respective team lead.

app/controllers/teamlead_controller.rb
class TeamleadController < ApplicationController
	before_action() { authorize! :access, :teamlead }
	before_action :find_requirement, only: [:make_task_tl, :tl_assign_to_multiple, :tl_assign, :add_task]
	before_action :find_id_in_teamlead, only: [:add_task]
	# ********************** Make Task show page ********************
	def make_task_tl
		authorize! :read, User
		@dp_tks = Task.where("requirement_id == ?  and (status_id is null or status_id == 1 or status_id==6)", params[:id]).order("updated_at DESC")
    	@tt_tks = Task.where("requirement_id == ?  and (status_id == 2 or status_id == 3 or status_id == 4 or status_id == 5)", params[:id]).order("updated_at DESC")

		@dps = User.where("teamlead_id = ? and usertype_id = 3", @rq.teamlead_id).order("updated_at DESC")
		@tts = User.where("teamlead_id = ? and usertype_id = 4", @rq.teamlead_id).order("updated_at DESC")	 
	end
	# **********************Assign multiple tasks to employee*******************
	def tl_assign_to_multiple
		authorize! :update, Task
		# **********************if both devlopers an testers are selected************
		if(params[:developer] != ""  and params[:tester] != "" )	
			flash[:notice] =  "You cannot select both developer and tester "
			redirect_to make_task_tl_path(@rq.id)
		else
			# *********If developer is selected ********************
			if (params[:developer] != "" && params[:tasks_ids] != nil)
				@user= params[:developer]
				@rq.users << @user							
				Task.where(id: params[:tasks_ids]).update_all developer_id:   params[:developer]
				Task.where(id: params[:tasks_ids]).update_all status_id: 1
	    		redirect_to make_task_tl_path(@rq.id)
	    		#==notifications
			      str="some tasks are assigned to you by TL: #{current_user.username}."
			      @n=Notification.create(:notice => str, :user_id => @user)
			      @n.save!


	    	# ********If tester is selected ************************
	    	elsif(params[:tester] != "" && params[:tasks_ids] != nil)
	    		@user= params[:tester]
	    		@rq.users << @user
	    		Task.where(id: params[:tasks_ids]).update_all tester_id: params[:tester]
	    		Task.where(id: params[:tasks_ids]).update_all status_id: 3
	    		redirect_to make_task_tl_path(@rq.id)
	    		#==notifications
			      str="some tasks are assigned to you by TL: #{current_user.username}."
			      @n=Notification.create(:notice => str, :user_id => @user)
			      @n.save!

	    	# If no task is selected or no employee is selected
			else 
				flash[:notice] =  "You Didn't selected any employee or task"
				redirect_to make_task_tl_path(@rq.id)
			end
		end
	end

	# ************************Assign Tasks ****************************
	def tl_assign
		authorize! :update, Task
		# **********************if both devlopers an testers are selected************
		if(params[:developer] != nil and params[:tester] != nil)	
			flash[:notice] =  "You cannot select both developer and tester "
			redirect_to make_task_tl_path(@rq.id)
		
		else
			# *********If developer is selected ********************
			if (params[:developer] != nil )	
				@user= params[:developer]
				@rq.users << @user						
				Task.where(id: params[:tasks_ids]).update_all developer_id:   params[:developer]
				Task.where(id: params[:tasks_ids]).update_all status_id: 1
	    		redirect_to make_task_tl_path(@rq.id)
	    		#==notifications			     
			      str="some tasks are assigned to you by TL: #{current_user.username}."
			      @n=Notification.create(:notice => str, :user_id => @user)
			      @n.save!

			# ********If tester is selected ************************
	    	elsif(params[:tester] != nil )
	    		@user= params[:tester]
	    		@rq.users << @user
	    		Task.where(id: params[:tasks_ids]).update_all tester_id: params[:tester]
	    		Task.where(id: params[:tasks_ids]).update_all status_id: 3
	    		redirect_to make_task_tl_path(@rq.id)
	    		#==notifications			      
			      str="some tasks are assigned to you by TL: #{current_user.username}."
			      @n=Notification.create(:notice => str, :user_id => @user)
			      @n.save!
			# If no task is selected or no employee is selected	    	
			else 
				flash[:notice] =  "You Didn't selected any employee or task"
				redirect_to make_task_tl_path(@rq.id)
			end
		end
	end
	
	#********************************Add task to requirement ***********************
	def add_task
		authorize! :create, Task
		@tasktype= Tasktype.all
		@dps = User.where("teamlead_id = ? and usertype_id = 3", Teamlead.find_by_username(current_user.username).id).order("updated_at DESC")
		@tts = User.where("teamlead_id = ? and usertype_id = 4", Teamlead.find_by_username(current_user.username).id).order("updated_at DESC")
		@task= Task.new
	end

	# ****************************All developers under this TL**************************
	def developer
		authorize! :read, User
		@dps = User.where("teamlead_id = ? and usertype_id = 3", Teamlead.find_by_username(current_user.username).id).order("updated_at DESC")
	end

	# ****************************All testers under this TL**************************
	def tester
		authorize! :read, User
		@tts = User.where("teamlead_id = ? and usertype_id = 4", Teamlead.find_by_username(current_user.username).id).order("updated_at DESC")
	end

	# ****************************Find requirement**************************
  	def find_requirement
  		@rq = Requirement.find(params[:id])
 	end

 	def find_id_in_teamlead
 		@teamlead= Teamlead.find_by_username(current_user.username)
 	end
	
end

app/helpers/teamlead_helper.rb
module TeamleadHelper
	def find_task_type(t)
		if t.of_issue? 
			@type= "Issue"
	    elsif t.of_change_request? 	    		
	    	@type= "Change Request"
	    else 
	    	@type= "Enhancement"
	    end 
	end

	def find_developer(t)
		if t.developer_id and (t.developer_id != t.teamlead_id)
			@user= User.find(t.developer_id).username
		else
			@user= "Not assigned"
		end
	end

	def find_tester(t)
		if t.tester_id and (t.tester_id != t.teamlead_id)
			@user= User.find(t.tester_id).username
		else
			@user= "Not assigned"
		end
	end

	def find_status(t)
		if(t.status_id==nil)
	    	@status= "Created"
    	elsif(t.assigned?)
    		@status= "Assigned"
    	elsif(t.marked?) 
    		@status= "Marked"
		elsif(t.on_review?)
    		@status= "On-Review"
    	elsif(t.reviewed?) 
    		@status= "Reviewed"
    	elsif(t.closed?) 
    		@status= "Closed"
    	elsif(t.reopened?) 
    		@status= "Reopened"
    	end
	end
end

app/views/teamlead/_task_table.html.erb
<tr>
  <th></th>
  <th>Task ID</th>
  <th>Task Name</th>
  <th>Task Type</th>
  <th>Assigned Date</th>
  <th>Developer Assigned </th>
  <th>Tester Assigned </th>
  <th>End Date</th>
  <th>Status</th>
  <th></th>
  <th></th>
</tr>

<% if @tks != nil %>
    <% @tks.each do |t| %>
	    <tr>
		  	<td>
		  		<% if !t.closed? %>
		  			<%= check_box_tag "tasks_ids[]", t.id %>
		  		<% end %>
		  	</td>

			<td><%= t.id%></td>

			<td><%= t.name %></td>

			<td> <%= find_task_type(t)%> </td>

			<td><%= t.updated_at.strftime(" %d-%m-%Y")  %></td>

			
			<td> <%= find_developer(t) %> </td>

			<td> <%= find_tester(t) %> </td>

			<td>
				<% if t.end != nil %>
		    		<%= t.end.strftime(" %d-%m-%Y") %>
		    	<% end %>
		    </td>
		    <td> <%=find_status(t)%> </td>

			<td><%= link_to ' Show ', task_path(t)%></td>

			<% if current_user.is_tlead?%>
				<td><%if !t.closed? %>
					<%=link_to ' Delete ', task_path(t), :method => :delete, data: {confirm: "Are you sure?"} %>
				<% end %></td>
				<% if t.reviewed? %>
					<td><%=link_to ' Close ', close_task_path(t), :method => :patch, data: {confirm: "Are you sure?"} %></td>
				<% end %>

			<% elsif current_user.is_admin?%>
				<% if t.closed? %>
				    <td><%=link_to ' Reopen ', reopen_task_path(t), :method => :patch, data: {confirm: "Are you sure?"} %></td>
				 <% end %>
			<% end %>

		</tr>
	<% end%>
<%end%>

app/views/teamlead/add_task.html.erb
<!--*********************************************** create new task*********************-->
<h2 style=" color:#aa2340;"> Project name: <%=link_to @rq.name , requirement_path(@rq), style: " color:#aa2340;" %>  </h1>
<h3> New Task </h2>

<%= simple_form_for(@task, :url => '/task', method: :post) do |t| %> 
	<fieldset>
		<div class="form-group">
			<%= t.input :name, label: "Task name", class: 'form-control'  %><br>
		</div>

		<div class="form-group">
			<%= t.input :description, label: "Description of task", class: 'form-control'  %><br>
		</div>
		<div class="form-group">
			<%= t.input :start, class: 'form-control'  %><br>
		</div>
		<div class="form-group">
			<%= t.input :end, class: 'form-control'  %><br>
		</div>
		<!-- ****************Type of task *********************-->
		<div class="form-group">
			<%= t.label :Type_of_task %>
			
			<%= t.collection_select :tasktype_id, @tasktype, :id, :ttype, class: 'form-control'  %><br>
		</div>
		<!-- ****************Hidden field for requirement_id and teamlead_id *********************-->
		<div class="form-group">
			<%= t.input :requirement_id, :as => :hidden, :input_html => { :value => @rq.id }%>
			<%= t.input :teamlead_id, :as => :hidden, :input_html => { :value => @teamlead.id }%>
		</div>
		<!-- ****************Assign developers *********************-->
		<div class="form-group">
			
			<%= t.label :Assign_Developer %>
			<%= t.collection_select :developer_id, @dps, :id, :username, :include_blank => "Developers", class: 'form-control'  %><br>
		</div>

		<div class="form-group">
			<%= t.label :Assign_Tester %>
			<%= t.collection_select :tester_id, @tts, :id, :username, :include_blank => "Testers", class: 'form-control'  %><br>
		</div>

		<div class="form-group">
			<%= t.button :submit %>
		</div>
	</fieldset>
<% end %>

app/views/teamlead/developer.html.erb
<div style="background-color:#fff;">		
	<table class="table table-hover" Style="overflow-x:auto ;overflow-y:auto ;">
		<tr>
	      <th>Developers</th>
	    </tr>
		<% for u in @dps %>
				<tr>
					<td><%= u.username %> </td>
				</tr>
		<% end %>
	</table>
</div>

app/views/teamlead/make_task_tl.html.erb
<%session[:return_to] ||= request.referer%>
<h4 class="bg-primary">Project Name - <a href=" /requirement/<%=@rq.id%>" style="color:white" ><%=@rq.name%></a> </h4>

<div class="column" style="background-color:#eee;" >
	    <h2>Tasks</h2>
    	<!--******************** Add task to current project******************** -->
		<%= button_to "Add Task", add_task_path(@rq), method: :get, class: "button"  %> 
		<!-- ************* Task table************-->
	    <div>
	    	<%= form_tag tl_assign_to_multiple_teamlead_index_path,  method: :put do %>
	  			<table class="table table-hover" Style="overflow-x:auto ;overflow-y:auto ;">
	  				<!-- ***************** Task alloted to developers*******************-->
	  				<tr>
 						<th colspan="3"> Developers</th>
 					</tr>
	  				<% @tks=@dp_tks # render task table%>
	  				<%= render 'task_table'  %>

	  				<% if (@dps != nil) # Assign developer to selected tasks%>
						<tr>
							<td colspan="5">
							<%= select_tag("developer", options_from_collection_for_select(@dps, "id", "username"),prompt: "Select Developers") %>
							<%= hidden_field_tag :id, @rq.id%>
							<%= submit_tag "Assign Task" , class:  "button"%>
							</td>
						</tr>
					<% end %>
					<tr><td></td></tr>
					<tr><td></td></tr>
					<!-- ***************** Task alloted to testers*******************-->
					<tr>
 						<th colspan="3"> Testers</th>
 					</tr>
					<% @tks=@tt_tks # render task table%>
	  				<%= render 'task_table' %>
					
					<% if (@tts != nil) # Assign tester to selected tasks%>
						<tr>
							<td colspan="5">
							<%= select_tag(:tester, options_from_collection_for_select(@tts, "id", "username"),prompt: "Select Testers") %>
							<%= hidden_field_tag :id, @rq.id%>
							<%= submit_tag "Assign Task" , class:  "button"%>
							</td>
						</tr>
					<% end %>
				</table>
			<% end%>
		</div>
	</div>
	<div>
		<%= link_to "Back", :back %>
	</div>

app/views/teamlead/tester.html.erb
<div style="background-color:#fff;">		
			<table class="table table-hover" Style="overflow-x:auto ;overflow-y:auto ;" >
				<tr>
			      <th>Testers</th>
			    </tr>
				<% for u in @tts %>
						<tr>
							<td><%= u.username %> </td>
						</tr>
				<% end %>
			</table>
</div>