config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, 	 :controllers => { :registrations => 'users/registrations', :sessions =>'users/sessions' }
  root "home#index"
  get 'home' => 'home#index'

  get '/notification' => 'home#notification', as: :notice
  delete '/notification/:id' => 'notification#destroy', as: :notification
  delete '/delete_all_notification/:id' => 'notification#delete_all', as: :delete_all

  resources :home, only: [:delete_notice] do
    collection do
      delete :delete_notice
    end
  end

  get 'admin/teamlead' => 'admin#teamlead'
  get 'admin/developers' => 'admin#developer'
  get 'admin/tester' => 'admin#tester'
  get 'admin/make_tt/:id' => 'admin#make_tt', as: :make_tt
  get 'admin/make_dp/:id' => 'admin#make_dp', as: :make_dp
  get 'assign_employee/:id' =>'admin#assign_employee', as: :assign_employee
   get 'admin/showa/:id' =>  'requirement#showa', as: :showa

  get 'teamlead/tester' => 'teamlead#tester'
  get 'teamlead/developers' => 'teamlead#developer'

  get 'make_task_tl/:id' => 'teamlead#make_task_tl', as: :make_task_tl

  resources :requirement
  patch 'admin/make_teamlead/:id' => 'admin#make_teamlead', as: :make_teamlead
  delete 'admin/employee/:id' => 'employee#destroy',        as: :admin_employee

  resources :task
  patch 'close_task/:id' => 'task#close_task', as: :close_task
  patch 'reopen_task/:id' => 'task#reopen_task', as: :reopen_task



  resources :teamlead, only: [:tl_assign_to_multiple] do
    collection do
      put :tl_assign_to_multiple
      put :tl_assign
    end
  end

  resources :admin, only: [:edit_project_multiple, :update_project_multiple] do
    collection do
      get :edit_project_multiple, as: :edit_project_multiple
      put :update_project_multiple, as: :update_project_multiple
      put :assign_employee_put,     as: :assign_employee_put
    end
  end

  resources :developer, only: [:done_multiple_update] do
    collection do
      put :done_multiple_update, as: :done_multiple_update
    end
  end

  resources :tester, only: [:done_multiple_update] do
    collection do
      put :done_multiple_update, as: :done_multiple_update
    end
  end

  

  get 'add_task/:id' => 'teamlead#add_task', as: :add_task
  
end

app/models/task.rb
class Task < ApplicationRecord

=begin
***Task Status***
status_id   | status
1-			Assigned
2- 			Marked
3-			On_review
4-			Reviewed
5-			Closed
6-			Reopened


***Task Type***
tasktype_id | Type
1-			Issue
2-			Change Request
3-			Enhancement
=end


	belongs_to :user, optional: true
	belongs_to :status, optional: true
	belongs_to :tasktype
	belongs_to :teamlead
	belongs_to :requirement
	has_many   :attachements

# *****************************************Task Status***********************
	def created?
		if self.status_id == nil
			return true
		else
			return false
		end
	end

	def assigned?
		if self.status_id == 1
			return true
		else
			return false
		end
	end

	def marked?
		if self.status_id == 2
			return true
		else
			return false
		end
	end

	def on_review?
		if self.status_id == 3
			return true
		else
			return false
		end
	end

	def reviewed?
		if self.status_id == 4
			return true
		else
			return false
		end
	end

	def closed?
		if self.status_id == 5
			return true
		else
			return false
		end
	end

	def reopened?
		if self.status_id == 6
			return true
		else
			return false
		end
	end
#***********

#****************************************Task type*******************************
	def of_issue?
		if self.tasktype_id == 1
			return true
		else
			return false
		end
	end

	def of_change_request?
		if self.tasktype_id == 2
			return true
		else
			return false
		end
	end

	def of_enhancement?
		if self.tasktype_id == 3
			return true
		else
			return false
		end
	end
#*******************************	

end

app/models/tasktype.rb
class Tasktype < ApplicationRecord
	has_many :tasks
end

=begin

***Task Type***
tasktype_id | Type
1-			Issue
2-			Change Request
3-			Emhancement
=end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  load_and_authorize_resource
	before_action :find_task, only: [:show, :edit, :update, :destroy, :reopen_task]

	
 	
	def index
  		@tks= Task.all.order("created_at DESC") 
  	end


	def create
    	@tk = Task.new(task_params)
      @rq= Requirement.find(@tk.requirement_id)
      if @tk.developer_id != nil
        @tk.status_id = 1
        if @rq.users.where(:id => @tk.developer_id).empty?
          @rq.users << User.find(@tk.developer_id)
        end
      else
        @tk.developer_id = @tk.teamlead_id
    	end

      if @tk.tester_id == nil
         @tk.tester_id = @tk.teamlead_id
      else
        if @rq.users.where(:id => @tk.tester_id).empty?
          @rq.users << User.find(@tk.tester_id)
        end
      end
     
    	if @tk.save!
    		flash[:notice] = "Task successfully created"
        # notifications
        
        str="New Task: '#{@tk.name}' is assigned to you"
        if @tk.developer_id != @tk.teamlead_id 
          @n=Notification.create(:notice => str, :user_id => @tk.developer_id)
          @n.save!
        end
        if @tk.tester_id != @tk.teamlead_id 
          @n=Notification.create(:notice => str, :user_id => @tk.tester_id)
          @n.save!
        end
	        redirect_to make_task_tl_path(@tk.requirement_id)
	    else	    	
	    	flash[:notice] = "Task not created"
	      redirect_to make_task_tl_path(@tk.requirement_id)
	    end
	end 

  def show
    if current_user.is_tlead?
    	@dps = User.where("teamlead_id = ? and usertype_id = 3", Teamlead.find_by_username(current_user.username).id).order("updated_at DESC")
      @tts = User.where("teamlead_id = ? and usertype_id = 4", Teamlead.find_by_username(current_user.username).id).order("updated_at DESC")
    end
  end 

  def edit
  	
  end 

  def update
  	
  	if @tk.update_attributes(task_params)
  		redirect_to(:action =>'show', :id => @tk.id)
  	else
  		render 'task/edit'
  	end
  end

  def destroy
  	@tk.destroy

    #==notifications
    @tl=User.find_by_username(current_user.username).id
    #For Admin
    str="Task no #{@tk.id}  of Project #{Requirement.find(@tk.requirement_id).name} has been deleted by you."
    @n=Notification.create(:notice => str, :user_id => @tl)
    @n.save!

    @rid= @tk.requirement_id
    redirect_to requirement_path(@rid)
  end

  def close_task
    
    @tks=Task.where(id: params[:id]).update status_id: 5
    @tks.each do |t|

      #==notifications
      @tl=User.find_by_username(current_user.username)
      #For teamlead
      str="Task no #{t.id}  of Project #{Requirement.find(t.requirement_id).name} has been closed by you."
      @n=Notification.create(:notice => str, :user_id => @tl.id)
      @n.save!
      #For admin
      str="Task no #{t.id}  of Project #{Requirement.find(t.requirement_id).name} has been closed by Team Lead: #{current_user.username}."
      @n=Notification.create(:notice => str, :user_id => User.find(@tl.teamlead_id).id)
      @n.save!
    end
      
    flash[:notice] =  "Task successfully closed "
    redirect_to task_path(params[:id])
    #
  end

  def reopen_task
    authorize! :update , Task
    if @tk.status_id == 5

      #==notifications
      Task.where(id: params[:id]).update status_id: 6
      @tl=User.find_by_username(Teamlead.find(@tk.teamlead_id).username).id
      #For teamlead
      str="Task no #{@tk.id}  of Project #{Requirement.find(@tk.requirement_id).name} has been reopened by Admin: #{current_user.username}."
      @n=Notification.create(:notice => str, :user_id => @tl)
      @n.save!
      #For admin
      str="Task no #{@tk.id}  of Project #{Requirement.find(@tk.requirement_id).name} has been reopened by you."
      @n=Notification.create(:notice => str, :user_id => current_user.id)
      @n.save!
      flash[:notice] =  "Task successfully reopened "
      redirect_to requirement_path(@tk.requirement_id)
    else
      flash[:notice] =  "Task is not closed "
      redirect_to requirement_path(@tk.requirement_id)
    end
  end
  

  def find_task
  	@tk = Task.find(params[:id])
  end

  private 
    def task_params 
    	 params.require(:task).permit(:name,:description,:avatar,:start,:end, :teamlead_id, :tasktype_id, :requirement_id, :developer_id, :tester_id)
end
end

app/helpers/task_helper.rb
module TaskHelper
	def find_task_type(t)
		if t.of_issue? 
			@type= "Issue"
	    elsif t.of_change_request? 	    		
	    	@type= "Change Request"
	    else 
	    	@type= "Enhancement"
	    end 
	end

	def find_project(t)
		@rq= Requirement.find(t.requirement_id).name
	end
	
	def find_developer(t)
		if t.developer_id and (t.developer_id != t.teamlead_id)
			@user= User.find(t.developer_id).username
		else
			@user= "Not assigned"
		end
	end

	def find_tester(t)
		if t.tester_id and (t.tester_id != t.teamlead_id)
			@user= User.find(t.tester_id).username
		else
			@user= "Not assigned"
		end
	end

	def find_status(t)
		if(t.status_id==nil)
	    	@status= "Created"
    	elsif(t.assigned?)
    		@status= "Assigned"
    	elsif(t.marked?) 
    		@status= "Marked"
		elsif(t.on_review?)
    		@status= "On-Review"
    	elsif(t.reviewed?) 
    		@status= "Reviewed"
    	elsif(t.closed?) 
    		@status= "Closed"
    	elsif(t.reopened?) 
    		@status= "Reopened"
    	end
	end
end

app/views/task/show.html.erb
<h2 > Name: <%= @tk.name %> </h2>
<!-- **************************Decription of task******************* -->
<div class="col-sm-12">
	<div class="well">
		Description:  <%= @tk.description %>
	</div>
</div>
<!-- **************************Type of task******************* -->
<div class="col-sm-3">
	<div class="well">
		Task Type:  
		<%= find_task_type(@tk) %>
	</div>
</div>
<!-- **************************Project name******************* -->
<div class="col-sm-3">
	<div class="well">
		Project name:  
		<%= find_project(@tk) %>
	</div>
</div>
<!-- **************************Updated at******************* -->
<div class="col-sm-3 ">
	<div class="well">
		Created: 
		<%= @tk.updated_at.strftime(" %d-%m-%Y")  %>
	</div>
</div>
<!-- **************************End date******************* -->
<div class="col-sm-3 ">
	<div class="well">
		Done upto:  
		<% if @tk.end != nil %>
	    	<td><%= @tk.end.strftime(" %d-%m-%Y") %></td>
	    <% end %>
    </div>
</div>
<!-- **************************If current user is tlead or admin ******************* -->
<% if current_user.is_tlead? or current_user.is_admin? or current_user.is_tester? %>

	<div class="col-sm-3 ">
		<div class="well">
			Developer Assigned:    
			<%= find_developer(@tk)%> 
		</div>
	</div>
<% end %>
<% if current_user.is_tlead? or current_user.is_admin? or current_user.is_developer? %>
	<div class="col-sm-3 ">
		<div class="well">
			Tester Assigned:    
			<%= find_tester(@tk)%> 
		</div>
	</div>
<% end%>
<!-- **************************Satatus of task******************* -->
<div class="col-sm-3 ">
	<div class="well">
	        Status:     
    	<%= find_status(@tk) %>
	</div>    	
</div>
<!-- *******************************************If current user is tlead***************************** -->
<% if current_user.is_tlead? %>
    <div class="col-sm-6 ">
		<div class="well">
			<%= form_tag tl_assign_teamlead_index_path,  method: :put do %>
			    <% if (@dps != nil) || (@tts != nil)%>
					<% if @tk.created? or @tk.assigned? or @tk.reopened?%>
						<%= select_tag("developer", options_from_collection_for_select(@dps, "id", "username"),prompt: "Select Developers") %>							
						<%= submit_tag "Assign Task" , class:  "button2"%>
						
					<%elsif @tk.marked? or @tk.on_review? %>
						<%= select_tag(:tester, options_from_collection_for_select(@tts, "id", "username"),prompt: "Select Testers") %>							
						<%= submit_tag "Assign Task" , class:  "button2"%>
					<% end%>
					<%= hidden_field_tag :id, @tk.requirement_id%>
					<%= hidden_field_tag :tasks_ids, @tk.id%>
					
				<%end%>
			<%end%>
		</div>
	</div>

    <br><br><br><br><br><br><br><hr>
    <% if @tk.created? or @tk.assigned? or @tk.marked? %>
		<%=button_to ' Delete this task ', task_path(@tk), :method => :delete, class: "button", data: {confirm: "Are you sure?"} %>
	<% end %>
<%end%>			