config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, 	 :controllers => { :registrations => 'users/registrations', :sessions =>'users/sessions' }
  root "home#index"
  get 'home' => 'home#index'

  get '/notification' => 'home#notification', as: :notice
  delete '/notification/:id' => 'notification#destroy', as: :notification
  delete '/delete_all_notification/:id' => 'notification#delete_all', as: :delete_all

  resources :home, only: [:delete_notice] do
    collection do
      delete :delete_notice
    end
  end

  get 'admin/teamlead' => 'admin#teamlead'
  get 'admin/developers' => 'admin#developer'
  get 'admin/tester' => 'admin#tester'
  get 'admin/make_tt/:id' => 'admin#make_tt', as: :make_tt
  get 'admin/make_dp/:id' => 'admin#make_dp', as: :make_dp
  get 'assign_employee/:id' =>'admin#assign_employee', as: :assign_employee
   get 'admin/showa/:id' =>  'requirement#showa', as: :showa

  get 'teamlead/tester' => 'teamlead#tester'
  get 'teamlead/developers' => 'teamlead#developer'

  get 'make_task_tl/:id' => 'teamlead#make_task_tl', as: :make_task_tl

  resources :requirement
  patch 'admin/make_teamlead/:id' => 'admin#make_teamlead', as: :make_teamlead
  delete 'admin/employee/:id' => 'employee#destroy',        as: :admin_employee

  resources :task
  patch 'close_task/:id' => 'task#close_task', as: :close_task
  patch 'reopen_task/:id' => 'task#reopen_task', as: :reopen_task



  resources :teamlead, only: [:tl_assign_to_multiple] do
    collection do
      put :tl_assign_to_multiple
      put :tl_assign
    end
  end

  resources :admin, only: [:edit_project_multiple, :update_project_multiple] do
    collection do
      get :edit_project_multiple, as: :edit_project_multiple
      put :update_project_multiple, as: :update_project_multiple
      put :assign_employee_put,     as: :assign_employee_put
    end
  end

  resources :developer, only: [:done_multiple_update] do
    collection do
      put :done_multiple_update, as: :done_multiple_update
    end
  end

  resources :tester, only: [:done_multiple_update] do
    collection do
      put :done_multiple_update, as: :done_multiple_update
    end
  end

  

  get 'add_task/:id' => 'teamlead#add_task', as: :add_task
  
end

app/views/admin/assign_employee.html.erb
<!-- Available unassigned employees****************-->
<div class="col-sm-6" style="background-color:#aaa;">
	<h4> Following are the available employees </h4>
	<div >
	    <%= form_tag assign_employee_put_admin_index_path,  method: :put do %> 
	  		<table >
			    <tr>
			      <th></th>
			      <th>User Name</th>
				</tr>
				<%  for e in @employees %>
					<tr>
						<td><%= check_box_tag "employee_ids[]", e.id %></td>
				    	<td><%= e.username%></td>
				    	<td><%= find_usertype(e) %></td>
				    </tr>
				<% end %>
			</table>
			<%= hidden_field_tag(:tid, @tl.id) %>
			<%= submit_tag "Assign",class:  "button" %>
		<% end %>
	</div>
</div>
<!--*************************-->

<!-- Employee under this team leader****************-->
<div class="col-sm-6" style="background-color:#ccc;padding-bottom: 40px; ">
	<h4>Employees under this TL </h4>
	<table >
		<tr>
	      <th>Employees</th>
	      <th></th>
	    </tr>
	    
		<% for e in @this_employees %>
			<tr>
				<td><%= e.username %> </td>
				<td><%= find_usertype(e)%></td>
			</tr>
		<% end %>
	</table>
</div>
<!--*************************-->

app/views/admin/developer.html.erb
<!-- All developers****************************-->
<div class="column" style="background-color:#fff;">
	<h2>Developers</h2>
	<table class="table table-hover" Style="overflow-x:auto ;overflow-y:auto ;">
		<tr>
	      <th>Developers</th>
	      <th>Assigned to</th>
	      <th> </th>
	      <th></th>
	    </tr>
		<% for u in @ds %>
			<tr>
				<td><%= u.username %> </td>
				<td><% if u.teamlead_id == default_user() %>
						<strong>Not under any TL</strong>
					<% else %>
						Assigned to <%=find_tlead(u) %>
					<% end %>
				</td>
				<td><%= link_to " Make Team Lead ", make_teamlead_path(u), method: :patch %></td>
				<td><%= link_to 'Delete Employee'  , admin_employee_path(u), method: :delete, data: {confirm: "Are you sure?"} %></td>
			</tr>
		<% end %>
	</table>
</div>

app/views/admin/edit_project_multiple.html.erb
<!-- Edit multiple selected projects******************-->
<h2> Edit Pojects </h2>
<%= form_tag  update_project_multiple_admin_index_path, method: :put do %>
	<%@rqs.each do |rq|%>
		<%= fields_for "projects[]", rq do |r| %>
			<br>
			<h3> Project : <%=rq.name %> </h3>

			<%= r.file_field :avatar %>

		  	<%= r.label :Project_Name %><br>
		  	<%= r.text_field :name %> <br>
			
			<%= r.label :Description %><br>
			<%= r.text_area :description %><br>
			
			<%= r.label :Last_Date %><br>
			<%= r.date_select :end %><br>

			<%= r.label :Teamlead %><br>
			
		    <%= r.collection_select :teamlead_id, @tl, :id, :username, prompt: " Select Team Lead " %><br>
			
		<% end %>
	<% end%>
	<%= submit_tag 'Edit Project' %>
<% end %>

app/views/admin/teamlead.html.erb
<!-- All team lead *****************-->
<div class="column" style="background-color:#fff;width:50%;">
	<h2>Team Leads assigned</h2>
	<table class="table table-hover" Style="overflow-x:auto ;overflow-y:auto ;" >
		<tr>
	      <th>Team Lead</th>
	      <th> </th>
	    </tr>
		<% for t in @tls %>
			<tr>
				<td><%= t.username %></td>
				<td><%= link_to 'Assign employees to TL', assign_employee_path(t) %>
			</tr>
		<% end %>
	</table>
</div>

app/views/admin/tester.html.erb
<!-- All testers *****************-->
<div class="column" style="background-color:#fff;">
	<h2>Testers</h2>
	<table class="table table-hover" Style="overflow-x:auto ;overflow-y:auto ;">
		<tr>
	      <th>Testers</th>
	      <th>Assigned to</th>
	      <th> </th>
	      <th></th>
	    </tr>
		<% for u in @ts %>
			<tr>
				<td><%= u.username %> </td>
				<td><% if u.teamlead_id == default_user() %>
						<strong>Not under any TL</strong>
					<% else %>
						Assigned to <%=find_tlead(u) %>
					<% end %>
				</td>
				<td><%= link_to " Make Team Lead ", make_teamlead_path(u), method: :patch %></td>
				<td><%= link_to 'Delete Employee'  , admin_employee_path(u), method: :delete, data: {confirm: "Are you sure?"} %></td>
			</tr>
		<% end %>
	</table>
</div>