config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, 	 :controllers => { :registrations => 'users/registrations', :sessions =>'users/sessions' }
  root "home#index"
  get 'home' => 'home#index'

  get '/notification' => 'home#notification', as: :notice
  delete '/notification/:id' => 'notification#destroy', as: :notification
  delete '/delete_all_notification/:id' => 'notification#delete_all', as: :delete_all

  resources :home, only: [:delete_notice] do
    collection do
      delete :delete_notice
    end
  end

  get 'admin/teamlead' => 'admin#teamlead'
  get 'admin/developers' => 'admin#developer'
  get 'admin/tester' => 'admin#tester'
  get 'admin/make_tt/:id' => 'admin#make_tt', as: :make_tt
  get 'admin/make_dp/:id' => 'admin#make_dp', as: :make_dp
  get 'assign_employee/:id' =>'admin#assign_employee', as: :assign_employee
   get 'admin/showa/:id' =>  'requirement#showa', as: :showa

  get 'teamlead/tester' => 'teamlead#tester'
  get 'teamlead/developers' => 'teamlead#developer'

  get 'make_task_tl/:id' => 'teamlead#make_task_tl', as: :make_task_tl

  resources :requirement
  patch 'admin/make_teamlead/:id' => 'admin#make_teamlead', as: :make_teamlead
  delete 'admin/employee/:id' => 'employee#destroy',        as: :admin_employee

  resources :task
  patch 'close_task/:id' => 'task#close_task', as: :close_task
  patch 'reopen_task/:id' => 'task#reopen_task', as: :reopen_task



  resources :teamlead, only: [:tl_assign_to_multiple] do
    collection do
      put :tl_assign_to_multiple
      put :tl_assign
    end
  end

  resources :admin, only: [:edit_project_multiple, :update_project_multiple] do
    collection do
      get :edit_project_multiple, as: :edit_project_multiple
      put :update_project_multiple, as: :update_project_multiple
      put :assign_employee_put,     as: :assign_employee_put
    end
  end

  resources :developer, only: [:done_multiple_update] do
    collection do
      put :done_multiple_update, as: :done_multiple_update
    end
  end

  resources :tester, only: [:done_multiple_update] do
    collection do
      put :done_multiple_update, as: :done_multiple_update
    end
  end

  

  get 'add_task/:id' => 'teamlead#add_task', as: :add_task
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  def index
    if current_user.present?
      if current_user.usertype_id ==1
    	 @rqs= current_user.requirements.order("updated_at DESC")
      elsif current_user.usertype_id == 2
        @rqs=Requirement.where("teamlead_id = ?", Teamlead.find_by_username(current_user.username).id ).order("updated_at DESC")
      elsif current_user.usertype_id == 3
        @tks= Task.where(:developer_id => current_user ).order("updated_at DESC")
      else
        @tks= Task.where(:tester_id => current_user ).order("updated_at DESC")
      end
    end
  end

  def notification
  	@notices= current_user.notifications.order("created_at DESC")
  end

  def delete_notice
  	Notification.where(:id => params[:notice_ids]).destroy_all
  	redirect_to '/notification'
  end
end

app/helpers/home_helper.rb
module HomeHelper
	def find_tlead(u)
		@tl=Teamlead.find(u.teamlead_id).username	
	end

	def find_task_type(t)
		if t.of_issue? 
			@type= "Issue"
	    elsif t.of_change_request? 	    		
	    	@type= "Change Request"
	    else 
	    	@type= "Enhancement"
	    end 
	end

	def find_project(t)
		@rq=Requirement.find(t.requirement_id).name
	end

	def find_status(t)
		if(t.status_id==nil)
	    	@status= "Created"
    	elsif(t.assigned?)
    		@status= "Assigned"
    	elsif(t.marked?) 
    		@status= "Marked"
		elsif(t.on_review?)
    		@status= "On-Review"
    	elsif(t.reviewed?) 
    		@status= "Reviewed"
    	elsif(t.closed?) 
    		@status= "Closed"
    	elsif(t.reopened?) 
    		@status= "Reopened"
    	end
	end
end

app/views/home/_task_table.html.erb
<tr>
  <th></th>
  <th>Task ID</th>
  <th>Task Name</th>
  <th>Task Type</th>
  <th>Project</th>
  <th>Assigned Date</th>
  <th>End Date</th>
  <th>Status</th>
  <th></th>
</tr>

<% if @tks != nil %>
    <% @tks.each do |t| %>
	    <tr>
		  	<td>
				<% if current_user.is_developer? %>
			    	<% if t.assigned? or t.marked? %>
			    		<%= check_box_tag "tasks_ids[]", t.id %>
					<% end%>
				<% elsif current_user.is_tester? %>
					<% if t.on_review? or t.reviewed? %>
			    		<%= check_box_tag "tasks_ids[]", t.id %>
					<% end%>
				<% end %>
			</td>

			<td><%=t.id%></td>

			<td><%= t.name %></td>

			<td> <%= find_task_type(t)%> </td>

			<td> <%= find_project(t) %> </td>

			<td><%= t.updated_at.strftime(" %d-%m-%Y")  %></td>

			<td>
				<% if t.end != nil %>
		    		<%= t.end.strftime(" %d-%m-%Y") %>
		    	<% end %>
		    </td>
		
		    <td> <%=find_status(t)%> </td>

			<td><%= link_to ' Show ', task_path(t)%></td>
		</tr>
	<% end%>
<%end%>

app/views/home/index.html.erb
<%session[:return_to] ||= request.referer%> <!--storing the url in the session hash, which is available across multiple requests -->


<!--***************************************************If current user is admin**********************************-->
<% if (current_user.present? )%> 
	<%if (current_user.is_admin? == true ) %>
		<%= button_to " New Project ","requirement/new",:method => :get , class: "button"%> <!-- Making new project -->
		<%= form_tag edit_project_multiple_admin_index_path, method: :get do %>
			<h4>All Projects</h4>
			<table class="table table-hover">
				<tr>
					<th></th>
					<th>Project ID</th>
					<th>Project Name</th>
					<th>Project description</th>
					<th>Last Date</th>
					<th>Team Lead</th>
					<th>Files</th>
					<th></th>
					<th></th>
				</tr>
				<% @rqs.each do |t| %>
					<tr>
						<td><%= check_box_tag "project_ids[]", t.id %></td>
						<td><%=t.id%></td>
						<td><%= t.name %></td>
						<td><%= truncate(t.description, length: 20) %></td>
						<td><% if t.end != nil %>
					    		<%= t.end.strftime(" %d-%m-%Y") %>
					    	<% end %>
						</td>
						<% if t.teamlead_id != nil %>
							<td><%= find_tlead(t) %></td>
						<% else %>
							<td>Not assigned </td>
						<%end%>
						<td><% if t.avatar.url != nil %>
								<%= link_to "Open", t.avatar.url, target: "_blank" %>	
							<% end %>
						</td>
						<td><%= link_to "Edit", edit_requirement_path(t) %></td>
						<td><%= link_to "Show", requirement_path(t) %></td>			    
					</tr>
				<% end %>
			</table>
			<%= submit_tag "Edit Selected" , class: "button"%>
		<% end %>

     <!--*********************************************If current user is team lead**********************************-->
	<%elsif current_user.is_tlead?%>
		<h4>All Projects</h4>
		<table class="table table-hover">
			<tr>
				<th></th>
				<th>Project ID</th>
				<th>Project Name</th>
				<th>Project description</th>
				<th>Last Date</th>
				<th>Files</th>
				<th></th>
				<th></th>
			</tr>
			<% @rqs.each do |t| %>
				<tr>
					<td><%= check_box_tag "project_ids[]", t.id %></td>
					<td><%= t.id%></td>
					<td><%= t.name %></td>
					<td><%= truncate(t.description, length: 20) %></td>
					<td><% if t.end != nil %>
					    	<%= t.end.strftime(" %d-%m-%Y") %>
					    <% end %>
					</td>
					<td><% if t.avatar.url != nil %>
							<%= link_to "Open", t.avatar.url, target: "_blank" %>	
						<% end %>
					</td>
					<td><%= link_to "Show", requirement_path(t) %></td>		
					<td><%= link_to "Make task ", make_task_tl_path(t), :method => :get %>
	 				</td>
				</tr>
			<% end %>
		</table>

	<!--*********************************************If current user is developer**************************************-->
	<%elsif current_user.is_developer? %>
		<div>
			<%= form_tag done_multiple_update_developer_index_path,  method: :put do %>
				<table class="table table-hover" Style="overflow-x:auto ;overflow-y:auto ;">
				    <%= render 'task_table'  %>		
				</table>
				<%= submit_tag "Toggle Tasks" %>
			<% end%>
		</div>
	<!--*********************************************If current user is tester **************************************-->
	<%elsif current_user.is_tester?%>
		<div>
			<%= form_tag done_multiple_update_tester_index_path,  method: :put do %>
				<table class="table table-hover" Style="overflow-x:auto ;overflow-y:auto ;">
				    <%= render 'task_table'  %>	
				</table>
				<%= submit_tag "Toggle Tasks" %>
			<% end%>
		</div>
	<% end %>
	<!--*********************************************If current user is guest user **************************************-->
<%else%>
	<h2>Please <%= link_to "Sign In", new_user_session_path  %> to continue.</h2>
<% end %>

app/views/home/notification.html.erb
<!-- ******************Form for deleting multiple selected ************-->
<%= form_tag delete_notice_home_index_path, method: :delete do %>
	<table class="table table-hover">
		<tr>
			<th></th>
			<th>Notifications</th>
			<th></th>
		</tr>
		<% @notices.each do |t| %>
			<tr>
				<td><%= check_box_tag "notice_ids[]", t.id %></td>
				<!-- ********If it was read earlier ************-->
				<%if t.checked == true %>
					<td><%= t.notice %></td>
				<!-- ********** If reading first time **********-->
				<% else %>
					<td><mark><%= t.notice %></mark></td>
				<%end%>
				<td><a rel="nofollow" data-method="delete" href="<%=notification_path(t)%>"><i class="glyphicon glyphicon-trash"></i></a>	</td>    
			</tr>
		<% end %>
	</table>
	<%= submit_tag "Delete Selected" ,data: {confirm: "Are you sure?"}, class: "button"%>
<% end %>
<!-- ****************** All notices are read ***************-->
<%@notices.update_all checked: true%>
<!-- *********************Delete all notices****************-->
<div style="margin: 2em 0 0 0">
	<%= button_to "Delete All", delete_all_path(current_user.id), method: :delete, data: {confirm: "Are you sure?"}, class: "danger"  %>
</div>